pop_size:
  description: 'the size of your population'
  value: 820000
  required: true

age_group_probs:
  description: 'the proportion of the population in each age group'
  value:
    child: 0.2
    adult: 0.6
    elderly: 0.2
  required: true

segment_probs_by_age_group:
  description: 'the proportion of the population in each segment, by age'
  value:
    child:
      Healthy: 0.8
      AcuteEpisodic: 0.15
      LongTermConditions: 0.05
      HighNeed: 0.0
      EndOfLife: 0.0
    adult:
      Healthy: 0.5
      AcuteEpisodic: 0.3
      LongTermConditions: 0.15
      HighNeed: 0.04
      EndOfLife: 0.01
    elderly:
      Healthy: 0.1
      AcuteEpisodic: 0.15
      LongTermConditions: 0.4
      HighNeed: 0.25
      EndOfLife: 0.1
  required: true

on_waiting_list_prob:
  description: 'the proportion of the proportion of the population on an elective waiting list, by age and segment'
  value:
    child:
      Healthy: 0.059
      AcuteEpisodic: 0.152
      LongTermConditions: 0.105
      HighNeed: 0.237
      EndOfLife: 0.163
    adult:
      Healthy: 0.043
      AcuteEpisodic: 0.151
      LongTermConditions: 0.133
      HighNeed: 0.289
      EndOfLife: 0.239
    elderly:
      Healthy: 0.083
      AcuteEpisodic: 0.224
      LongTermConditions: 0.178
      HighNeed: 0.243
      EndOfLife: 0.178
  required: true

elective_wait_times:
  description: 'median and 90th percentile waiting times'
  value:
    median: 100
    q90: 290
  required: true

gp_appointments_per_year:
  description: 'yearly average number of GP appointments by age and segment'
  value:
    child:
      Healthy: 1.9
      AcuteEpisodic: 5.2
      LongTermConditions: 3.4
      HighNeed: 7.5
      EndOfLife: 9.8
    adult:
      Healthy: 2.4
      AcuteEpisodic: 5.6
      LongTermConditions: 7.8
      HighNeed: 17.2
      EndOfLife: 16.2
    elderly:
      Healthy: 5.5
      AcuteEpisodic: 10.1
      LongTermConditions: 11.5
      HighNeed: 17
      EndOfLife: 18.7

gp_appointments_daily_weight:
  description: 'proportion of GP appointments per day'
  value:
    monday: 0.215
    tuesday: 0.208
    wednesday: 0.13
    thursday: 0.190
    friday: 0.181
    saturday: 0.012
    sunday: 0.001

ae_appointments_per_year:
  description: 'yearly average number A&E attendances by age and segment'
  value:
    child:
      Healthy: 0.4
      AcuteEpisodic: 2.6
      LongTermConditions: 0.7
      HighNeed: 1.3
      EndOfLife: 1.0
    adult:
      Healthy: 0.2
      AcuteEpisodic: 2.0
      LongTermConditions: 0.4
      HighNeed: 1.1
      EndOfLife: 1.0
    elderly:
      Healthy: 0.1
      AcuteEpisodic: 2.1
      LongTermConditions: 0.4
      HighNeed: 1.0
      EndOfLife: 1.0
