#' Simulate a day
#'
#' @param pop df generated by `generate_pop`
#' @param day a day of the week, lowercase as per params file
#' @param params params file
#'
#' @returns a data frame with outcomes appended
#' @export
#'
#' @examples
#' sim_day(pop,'wednesday',params)


sim_day <- function (pop,day,params)
{
  day_prob <- as.numeric(params$gp_appointments_daily_weight$value[day])


  df_gp_app <- as_tibble(params$gp_appointments_per_year$value) |> unnest()
  df_gp_app$segment <- names(params$gp_appointments_per_year$value$child)
  df_gp_app <- df_gp_app |>
    pivot_longer(child:elderly, names_to = 'age',values_to = 'appointments') |>
    mutate(appointment_prob = (appointments/52)*day_prob) |>
    select(-appointments)

  out <- pop |>
    left_join(df_gp_app) |>
    mutate(gp_app = rbinom(params$pop_size$value, 1, appointment_prob)) |>
    select(-appointment_prob)

  return(out)
}


